version: "3.9"
services:
  grafana:
    container_name: log-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always
  prometheus:
    container_name: log-prometheus
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: always
  exporter:
    container_name: log-exporter
    image: mypython
    build: .
    environment:
      TZ: Asia/Shanghai
    working_dir: /usr/src/app
    volumes:
      - ".:/usr/src/app"
    entrypoint: [ "python", "exportee.py" ]
    ports:
      - "5000:5000"
    restart: always

